name: aicerts_video_player
description: "Video Player for AI Certs"
version: 0.0.1
homepage: "https://github.com/aicerts-ai/aicerts_video_player"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  better_player_plus: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
